version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.2-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - run:
          name: Lint
          command: ng lint @yellowspot/ng-truncate
      - run:
          name: Unit Test
          command: ./node_modules/@angular/cli/bin/ng test --watch false @yellowspot/ng-truncate
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
